### ISSUE TITLE
First user not marked as administrator

### ISSUE THREAD

**Issue by boetter** [heroku/mobile-template1#19]
Been playing around with this for a bit, but no matter what I do I can't seem to log in as "admin". Being the first user doesn't give me any more rights than the second or third user. And accessing /admin/ just brings up "Invalid token". Any clues?

I've just made a simple click on the Heroku button, so it might be the config that needs something.

**Comment by boetter** [comment]
Hmm, logging in and out a few times fixed this. Odd, but closing for now.

**Comment by scottpersinger** [comment]
Theoretically this callback queries for the count of users during User.save and if there are no users yet, then it sets 'is_admin' on the model before the save. So first thing would be to look in the db after the initial "Register" and verify that the flag is set:

https://github.com/heroku/mobile-template1/blob/03ab8a45d956f7780001828b418d8c7560d0d2cd/server/models.js#L14
